// SPDX-FileCopyrightText: 2023 MishaUnity <81403616+MishaUnity@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 DakotaGay <dakotagay@disroot.org>
// SPDX-FileCopyrightText: 2024 Julian Giebel <juliangiebel@live.de>
// SPDX-FileCopyrightText: 2025 AgentePanela <agentepanela@gmail.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 GabyChangelog <agentepanela2@gmail.com>
// SPDX-FileCopyrightText: 2025 Kyoth25f <kyoth25f@gmail.com>
// SPDX-FileCopyrightText: 2025 SX-7 <sn1.test.preria.2002@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Message;
using Content.Shared.MassMedia.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System.Globalization;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using Content.Shared._Gabystation.CartridgeLoader.Cartridges;

namespace Content.Client._Gabystation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoBankUiFragment : BoxContainer
{
    /*public event Action? OnNextButtonPressed;
    public event Action? OnPrevButtonPressed;*/
    private bool _notificationsMuted;
    private float _nextPayment = 0f;

    public event Action<NanoBankUiMessageType, int?, int?>? OnMessageSent;

    public NanoBankUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        MuteButton.OnPressed += _ =>
        {
            _notificationsMuted = !_notificationsMuted;
            UpdateMuteButton();
            OnMessageSent?.Invoke(NanoBankUiMessageType.ToggleMute, null, null);
        };

        LoginButton.OnPressed += _ => HandleLogin();

        LogoffButton.OnPressed += _ =>
        {
            OnMessageSent?.Invoke(NanoBankUiMessageType.Logout, null, null);
        };

        TransferButton.OnPressed += _ => HandleTransfer();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        if (_nextPayment >= 0f)
            _nextPayment -= args.DeltaSeconds;

        Payout.Text = Loc.GetString("nanobank-fragment-payoff", ("time", ((int) _nextPayment).ToString()));
    }
    private void HandleLogin()
    {
        if (string.IsNullOrWhiteSpace(LoginId.Text) || string.IsNullOrWhiteSpace(LoginPin.Text))
            return;

        if (!int.TryParse(LoginId.Text, NumberStyles.Integer, CultureInfo.InvariantCulture, out var id))
            return;

        if (!int.TryParse(LoginPin.Text, NumberStyles.Integer, CultureInfo.InvariantCulture, out var pin))
            return;

        OnMessageSent?.Invoke(NanoBankUiMessageType.Login, id, pin);
        LoginPin.Text = "";
    }
    private void HandleTransfer()
    {
        if (string.IsNullOrWhiteSpace(TransferId.Text) || string.IsNullOrWhiteSpace(TransferAmount.Text))
            return;

        if (!int.TryParse(TransferId.Text, NumberStyles.Integer, CultureInfo.InvariantCulture, out var target))
            return;

        if (!int.TryParse(TransferAmount.Text, NumberStyles.Integer, CultureInfo.InvariantCulture, out var amount))
            return;

        OnMessageSent?.Invoke(NanoBankUiMessageType.Transfer, target, amount);
        // todo: clear this with fallback
        TransferId.Text = "";
        TransferAmount.Text = "";
    }

    public void UpdateState(NanoBankUiState state)
    {
        App.Visible = state.Logged;
        Login.Visible = !state.Logged;

        _notificationsMuted = state.NotificationsMuted;
        _nextPayment = state.NextPayment;
        AccountId.Text = $"#{state.AccountId:D4}";
        Balance.Text = Loc.GetString("nanobank-fragment-balance", ("balance", state.Balance.ToString()));

        UpdateMuteButton();
    }

    private void UpdateMuteButton()
    {
        if (BellMutedIcon != null)
            BellMutedIcon.Visible = _notificationsMuted;
    }
}
