// SPDX-FileCopyrightText: 2025 AgentePanela <agentepanela@gmail.com>
// SPDX-FileCopyrightText: 2025 GabyChangelog <agentepanela2@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Gabystation.ATM;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Gabystation.ATM;

[GenerateTypedNameReferences]
public sealed partial class BankATMWindow : DefaultWindow
{
    public BankATMWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("bank-atm-menu-title");
    }

    public void UpdateState(BankATMBuiState s)
    {
        WCard.Visible = s.HasCard;
        NoCard.Visible = !s.HasCard;

        var balanceMsg = new FormattedMessage();
        var accountId = $"#{s.AccountId:D4}";
        balanceMsg.AddMarkupPermissive(Loc.GetString("bank-atm-ui-balance", ("balance", s.Balance), ("account", accountId)));
        BalanceLabel.SetMessage(balanceMsg);

        var depositMsg = new FormattedMessage();
        if (s.MoneyInside is null || s.MoneyInside <= 0)
            depositMsg.AddMarkupPermissive(Loc.GetString("bank-atm-ui-deposit-label-alt"));
        else
            depositMsg.AddMarkupPermissive(Loc.GetString("bank-atm-ui-deposit-label", ("amount", s.MoneyInside)));
        DepositLabel.SetMessage(depositMsg);
    }
}
